name: niyama
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  animated_custom_dropdown: ^3.1.1
  flutter:
    sdk: flutter
  flutter_toggle_tab: ^1.5.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  icons_plus: ^5.0.0
  intl: ^0.19.0
  percent_indicator: ^4.2.5
  table_calendar: ^3.1.3
  time_picker_spinner_pop_up: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.9
  hive_generator: ^2.0.1


flutter:
  uses-material-design: true
